### ISSUE TITLE
Maven version format is non standard?

### ISSUE THREAD

**Issue by owen-c** [cerbos/cerbos-sdk-java#30]
Had a bit of trouble adding this to my dependencies because of the leading "v" which seems to be pretty non-standard in java land. Or maybe I just don't know what I'm doing :)

Consider adding this to the setup instructions or publish your versions as "0.5.1" with no v?

```
implementation("dev.cerbos:cerbos-sdk-java:v0.5.1")
```

**Comment by charithe** [comment]
Thanks for reporting. We've released `0.5.2` without the `v`. https://central.sonatype.com/artifact/dev.cerbos/cerbos-sdk-java/0.5.2
